### ISSUE TITLE
avro schema namespace is missing

### ISSUE THREAD

**Issue by denis-yuen** [common-workflow-language/common-workflow-language#178]
Not sure if this is a common-workflow-language or a schema-salad issue. Compiling with the current versions results in an avro schema with no namespace.

ex:
```
root@41cd8c875c1a:/common-workflow-language# git log | head -n3
commit f325a59a35c6970ac94a065bb7d6c01e37c13484
Author: Peter Amstutz <peter.amstutz@curoverse.com>
Date:   Fri Jan 8 14:40:39 2016 -0500
root@41cd8c875c1a:/common-workflow-language# python -mschema_salad --print-avro draft-3/CommonWorkflowLanguage.yml  > cwl.avsc
/root/.local/lib/python2.7/site-packages/schema_salad/__main__.py 1.4.20160108200836
root@41cd8c875c1a:/common-workflow-language# grep namespace cwl.avsc
root@41cd8c875c1a:/common-workflow-language# 
```

My understanding is that a namespace (like io.github.common-workflow-language or org.common.wl ) is best practice to avoid a conflict if a program uses two schema from different sources with the same name.  ex: https://avro.apache.org/docs/1.7.7/gettingstartedjava.html#Defining+a+schema 

In Java, this has the added side-effect of creating generated classes (when doing something like `java -jar avro-tools-1.7.7.jar compile schema cwl.edited.avsc cwl-temp`) in the default package which are difficult to work with. 

The current workaround is to do something like `sed -i '1i package cwl;' cwl-temp/*` to prepend a package name to all generated classes.

**Comment by denis-yuen** [comment]
https://github.com/common-workflow-language/schema_salad/issues/7 may be related. 

The avro schema uses illegal characters for the versions of the draft.

```
root@41cd8c875c1a:/# java -jar avro-tools-1.7.7.jar compile schema cwl.avsc cwl
Input files to compile:
  cwl.avsc
Exception in thread "main" org.apache.avro.SchemaParseException: Illegal character in: draft-3.dev1
	at org.apache.avro.Schema.validateName(Schema.java:1083)
	at org.apache.avro.Schema.access$200(Schema.java:79)
	at org.apache.avro.Schema$EnumSchema.<init>(Schema.java:684)
```

To alaborate, both the `.` and `-` seem problematic.

**Comment by pgrosu** [comment]
Hi Denis,

You are right, it is because of the period and dash, which cannot be part of an Enum.  It is something also encountered and had to write a check for it in my SDK code.  The issue is that periods in Java usually denote class/method/variable lookups - which you already know - but writing it for completeness' sake :)   Below is a link in the code where I perform this remap:

https://github.com/common-workflow-language/cwljava/blob/master/WIP/paul/CWLSDKBuilder.java#L519-L542

which results in the following result in the [CWLVersions.java](https://github.com/common-workflow-language/cwljava/blob/master/WIP/paul/sdk/CWLVersions.java) file:

```
public enum CWLVersions {

  draft3_dev1, draft3_dev2, draft3_dev3

}
```

The dash is also something I had to remove via the `getObjectSymbols()` method in the [YAMLParser.java](https://github.com/common-workflow-language/cwljava/blob/master/WIP/paul/YAMLParser.java), since it is interpreted as a minus between variable names.  Below is a link where I perform this:

https://github.com/common-workflow-language/cwljava/blob/master/WIP/paul/YAMLParser.java#L436-L438

Hope it helps,
`p

**Comment by mr-c** [comment]
@tetron This seems doable, yes?
