### ISSUE TITLE
cwtool generates a TypeError

### ISSUE THREAD

**Issue by kern3020** [common-workflow-language/common-workflow-language#19]
When I run 

	$ python ./reference/cwltool/main.py examples/bwa-mem-tool.json examples/bwa-mem-job.json 

This error is generated. 

	bwa mem -t4 -I1,2,3,4 -m 3 /tmp/job983894154_test-files/chr20.fa /tmp/job983894\
	154_test-files/example_human_Illumina.pe_1.fastq /tmp/job983894154_test-files/e\
	xample_human_Illumina.pe_2.fastq > output.sam
	Traceback (most recent call last):
	  File "./reference/cwltool/main.py", line 53, in <module>
	    sys.exit(main())
	  File "./reference/cwltool/main.py", line 44, in main
	    print job.run(dry_run=args.dry_run)
	  File "/home/jkern/src/common-workflow-language/reference/cwltool/job.py", lin\
	e 23, in run
	    subprocess.call("docker", "pull", self.container["uri"])
	  File "/usr/lib/python2.7/subprocess.py", line 522, in call
	    return Popen(*popenargs, **kwargs).wait()
	  File "/usr/lib/python2.7/subprocess.py", line 659, in __init__
	    raise TypeError("bufsize must be an integer")
	TypeError: bufsize must be an integer

Submitting PR.

**Comment by tetron** [comment]
Fixed in master
