### ISSUE TITLE
dockerFile should be a string or IRI, not just a string

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#294]
To enable non CWL systems to make use of an otherwise embedded `dockerFile` this field should be allowed to contain an IRI/URL, not just the Dockerfile contents.

http://www.commonwl.org/v1.0/CommandLineTool.html#DockerRequirement

Example that can't be parsed by third party tools: https://github.com/common-workflow-language/workflows/blob/master/tools/GATK-docker.yml#L2

**Comment by tetron** [comment]
For the above example, one can use `$import` to include the Dockerfile as external text.

However, if the Dockerfile needs to import files into the container (using "ADD") then a better solution would be to allow `dockerFile` to be a `File` object, which can bring secondaryFiles with it.

**Comment by mr-c** [comment]
We have the first user case, thanks for the reminder!

**Comment by mr-c** [comment]
Hey @tetron , `$import` isn't working here

```
Traceback (most recent call last):
  File "/home/michael/src/h3abionet16S/env/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 554, in resolve_all
    val, base_url, file_base=file_base, checklinks=False)
  File "/home/michael/src/h3abionet16S/env/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 496, in resolve_all
    return self.resolve_ref(document, base_url=file_base, checklinks=checklinks)
  File "/home/michael/src/h3abionet16S/env/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 324, in resolve_ref
    doc = self.fetch(doc_url, inject_ids=(not mixin))
  File "/home/michael/src/h3abionet16S/env/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 636, in fetch
    raise validate.ValidationException("Syntax error %s" % (e))
ValidationException: Syntax error did not find expected <document start>
  in "file:///home/michael/workflows/tools/alea-Dockerfile", line 22, column 1
```
alea-docker.yml 
``` yml
class: DockerRequirement
dockerPull: scidap/alea:v1.2.2
#dockerImageId: scidap/alea:v1.2.2 #not yet ready
dockerFile:
 $import: alea-Dockerfile
```
alea-Dockerfile 
``` yml
#################################################################
# Dockerfile
#
# Software:         Alea
# Software Version: 1.2.2
# Description:      Alea image for SciDAP
# Website:          http://scidap.com/
# Provides:         alea|bwa|Plink|vcftools|bedGraphToBigWig|shapeit2
# Base Image:       scidap/scidap:v0.0.1
# Build Cmd:        docker build --rm -t scidap/alea:v1.2.2 .
# Pull Cmd:         docker pull scidap/alea:v1.2.2
# Run Cmd:          docker run --rm scidap/alea:v1.2.2 alea
#################################################################

### Base Image
FROM scidap/scidap:v0.0.1
MAINTAINER Andrey V Kartashov "porter@porter.st"
ENV DEBIAN_FRONTEND noninteractive
[...]
```

**Comment by mr-c** [comment]
Nevermind, I forgot the `>` after `dockerFile:`

```
class: DockerRequirement
dockerPull: scidap/alea:v1.2.2
#dockerImageId: scidap/alea:v1.2.2 #not yet ready
dockerFile: >
 $import: alea-Dockerfile
```

**Comment by tetron** [comment]
@mr-c this definitely won't work, this will give you the string literal `"$import: alea-Dockerfile"`

```
dockerFile: >
 $import: alea-Dockerfile
```

But I made a mistake, you want is `$include`:

```
 dockerFile:
 $include: alea-Dockerfile
```

**Comment by mr-c** [comment]
I don't know of any implementation that uses the Dockerfile field yet, but
I will investigate further.

Pe 26 aug. 2016 9:06 p.m., "Peter Amstutz" <notifications@github.com> a
scris:
