### ISSUE TITLE
Tutorial inconcistencies

### ISSUE THREAD

**Issue by karl616** [common-workflow-language/common-workflow-language#318]
Hi,

I'm working my way through the tutorial. There are some inconcistencies:

inp.cwl:
The relative reference to whale.txt ends up pointing to a temporary file. Perhaps it is correct, but in that case, it is a bit confusing:

```
$ cwl-runner inp.cwl inp-job.yml 
/home/user/.local/bin/cwl-runner 1.0.20161005195021
[job inp.cwl] /tmp/tmpQqlLCI$ echo \
    -f \
    -i42 \
    --example-string \
    hello \
    --file=/tmp/tmpnyc4f3/stg3021f5c0-db22-4afe-824d-125054be4230/whale.txt
-f -i42 --example-string hello --file=/tmp/tmpnyc4f3/stg3021f5c0-db22-4afe-824d-125054be4230/whale.txt
Final process status is success
{}
```

Section 2.12 requires that node.js is installed. Not hard to figure out, but would be easier if it was mentioned. Secondly, it is unclear what the content of empty.yml is. While the command works without empty.yml, given an empty file (touch empty.yml) cwl-runner fails:

```
$ rm empty.yml && touch empty.yml
$ cwl-runner expression.cwl empty.yml 
/home/user/.local/bin/cwl-runner 1.0.20161005195021
Traceback (most recent call last):
  File "/home/user/.local/bin/cwl-runner", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/cwltool/main.py", line 682, in main
    make_fs_access=make_fs_access)
  File "/home/user/.local/lib/python2.7/site-packages/cwltool/main.py", line 487, in load_job_order
    if "cwl:tool" in job_order_object:
TypeError: argument of type 'NoneType' is not iterable

```

I also have to say I miss some more explanation with the tool examples towards the end. I understand that will come with time though.

Best,
Karl

**Comment by karl616** [comment]
Another thing, there is no explanation to when and how to use "-" at the beginning of a line. It pops up from time to time. I guess it is linked to underlying formats. Sorry for not being familiar enough with them. I would appreciate a more throughout explanation.

**Comment by kmhernan** [comment]
hmm isn't the `-` just part of the normal YAML format? You would use `-` or `[]` but nested mappings can be done like:

```
Person:
    name: Bob
    age: 25
```

This could be useful https://learnxinyminutes.com/docs/yaml/

Although maybe i'm misunderstanding the question

**Comment by karl616** [comment]
Thanks! The styles are mixed in section 2.10. As this is about the only place the - appears, I, lacking yaml knowledge, tried to read extra functionality into the symbol.
