### ISSUE TITLE
kallisto workflow is incompatible with Rabix composer

### ISSUE THREAD

**Issue by yyoshiaki** [common-workflow-language/common-workflow-language#804]
Hello,

I tried kallisto workflows using community maintained workflows and rabix composer and encountered several errors.

First, [kallisto-demo.cwl](https://github.com/common-workflow-language/workflows/blob/master/workflows/kallisto-demo.cwl) failed with the error below.

```
[2018-11-28 12:57:16.979] [ERROR] Encountered an error while starting local backend.
org.rabix.engine.service.JobServiceException: Failed to create Bindings
    at org.rabix.engine.service.impl.JobServiceImpl.start(JobServiceImpl.java:173) ~[rabix-cli.jar:na]
    at org.rabix.cli.BackendCommandLine.main(BackendCommandLine.java:418) ~[rabix-cli.jar:na]
Caused by: java.lang.NullPointerException: null
    at org.rabix.bindings.cwl.bean.CWLJobApp.setHint(CWLJobApp.java:157) ~[rabix-cli.jar:na]
    at org.rabix.bindings.cwl.CWLJobProcessor.processHints(CWLJobProcessor.java:86) ~[rabix-cli.jar:na]
    at org.rabix.bindings.cwl.CWLJobProcessor.process(CWLJobProcessor.java:65) ~[rabix-cli.jar:na]
    at org.rabix.bindings.cwl.CWLJobProcessor.process(CWLJobProcessor.java:36) ~[rabix-cli.jar:na]
    at org.rabix.bindings.cwl.helper.CWLJobHelper.getCWLJob(CWLJobHelper.java:26) ~[rabix-cli.jar:na]
    at org.rabix.bindings.cwl.CWLTranslator.translateToDAG(CWLTranslator.java:35) ~[rabix-cli.jar:na]
    at org.rabix.bindings.cwl.CWLBindings.translateToDAG(CWLBindings.java:160) ~[rabix-cli.jar:na]
    at org.rabix.engine.service.impl.JobServiceImpl.lambda$start$3(JobServiceImpl.java:150) ~[rabix-cli.jar:na]
    at org.rabix.engine.store.memory.InMemoryRepositoryRegistry.doInTransaction(InMemoryRepositoryRegistry.java:92) ~[rabix-cli.jar:na]
    at org.rabix.engine.service.impl.JobServiceImpl.start(JobServiceImpl.java:139) ~[rabix-cli.jar:na]
    ... 1 common frames omitted
```

I made sure that tools/kallisto-index.cwl and tools/kallisto-quant.cwl themselves worked well using rabix composer. Then I tried to compose a similar workflow and another error occurred...

```
[2018-12-01 01:11:51.378] [INFO] Trying to find cached results in the directory rabix-cache/root/.kallisto_quant.meta
[2018-12-01 01:11:51.378] [INFO] Cache directory doesn't exist. Directory rabix-cache/root/.kallisto_quant.meta
[2018-12-01 01:11:51.397] [DEBUG] Collecting outputs for root.kallisto_quant.
[2018-12-01 01:11:51.401] [INFO] Glob service didn't find any files.
[2018-12-01 01:11:51.427] [INFO] Job root.kallisto_quant failed with exit code 1. with message: 
Error: kallisto index file missing


[2018-12-01 01:11:51.429] [DEBUG] Job root.kallisto_quant, rootId: 658fa103-f0e3-46c7-8071-d72cbfe94f50 failed: Job root.kallisto_quant failed with exit code 1. with message: 
Error: kallisto index file missing


[2018-12-01 01:11:51.429] [DEBUG] handleUnusedFiles of 658fa103-f0e3-46c7-8071-d72cbfe94f50: []
[2018-12-01 01:11:51.429] [DEBUG] handleUnusedFilesIfAny(658fa103-f0e3-46c7-8071-d72cbfe94f50)
[2018-12-01 01:11:51.429] [DEBUG] onJobFailed(jobId=b2ce97da-22fd-3dc8-a2ce-0fb68ce361b4)
[2018-12-01 01:11:51.429] [INFO] Composer: {  "message" : "Job root.kallisto_quant failed with exit code 1. with message: \nError: kallisto index file missing\n\n",  "status" : "FAILED",  "stepId" : "root.kallisto_quant"}
[2018-12-01 01:11:51.432] [DEBUG] Root job 658fa103-f0e3-46c7-8071-d72cbfe94f50 failed. Job root.kallisto_quant failed with exit code 1. with message: 
Error: kallisto index file missing
```

I summerized cwl files and datasets [https://github.com/yyoshiaki/cwl_user_guide/tree/master/errors](https://github.com/yyoshiaki/cwl_user_guide/tree/master/errors).

and this is the composed workflow.

```
class: Workflow
cwlVersion: v1.0
id: kallisto_pe
label: kallisto-pe
$namespaces:
  sbg: 'https://www.sevenbridges.com'
inputs:
  - id: fastqs
    type: 'File[]'
    'sbg:x': -205.7967529296875
    'sbg:y': 139.5
  - id: fasta-files
    type: 'File[]'
    'sbg:x': -352
    'sbg:y': -26
outputs:
  - id: quantification
    outputSource:
      - kallisto_quant/quantification
    type: File
    'sbg:x': 107
    'sbg:y': 96
steps:
  - id: kallisto_index
    in:
      - id: fasta-files
        source:
          - fasta-files
    out:
      - id: index
    run: ./kallisto-index.cwl
    'sbg:x': -181
    'sbg:y': -25
  - id: kallisto_quant
    in:
      - id: fastqs
        source:
          - fastqs
      - id: index
        source: kallisto_index/index
    out:
      - id: quantification
    run: ./kallisto-quant.cwl
    'sbg:x': -16.7967529296875
    'sbg:y': 91.5
requirements: []
```

**Comment by mr-c** [comment]
Hello @yyoshiaki  and thank you for your issue.

I can confirm that the CWL reference runner (`cwltool`) thinks that the original workflow is valid.

Problems with the Rabix Composer are best reported to https://github.com/rabix/composer/issues/new so I've moved it for you: https://github.com/rabix/composer/issues/418
