### ISSUE TITLE
ERROR: genrsa: Can't open "/etc/apache2/ssl/pass.key" for writing, Read-only file system

### ISSUE THREAD

**Issue by Johnnywang92** [common-workflow-language/common-workflow-language#831]
when I run the cwl tools on MAC, I gat an error message as following. Any suggestion? 
```
genrsa: Can't open "/etc/apache2/ssl/pass.key" for writing, Read-only file system
[job bwa_index.cwl] Max memory used: 0MiB
[job bwa_index.cwl] Job error:
Error collecting output for parameter 'output':
bwa_index.cwl:30:5: Traceback (most recent call last):
bwa_index.cwl:30:5:
bwa_index.cwl:30:5:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 612, in collect_output_ports
bwa_index.cwl:30:5:     compute_checksum=compute_checksum)
bwa_index.cwl:30:5:
bwa_index.cwl:30:5:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 692, in collect_output
bwa_index.cwl:30:5:     raise
bwa_index.cwl:30:5:
bwa_index.cwl:30:5:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/schema_salad/sourceline.py", line 166, in __exit__
bwa_index.cwl:30:5:     raise self.makeError("\n".join(traceback.format_exception(exc_type, exc_value, tb)))
bwa_index.cwl:30:5:
WorkflowException: bwa_index.cwl:33:7: Traceback (most recent call last):
bwa_index.cwl:33:7:
bwa_index.cwl:33:7:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 664, in collect_output
bwa_index.cwl:33:7:     if gb.startswith(outdir):
bwa_index.cwl:33:7:
bwa_index.cwl:33:7: AttributeError: 'CommentedMap' object has no attribute 'startswith'
[job bwa_index.cwl] completed permanentFail
[job bwa_index.cwl] {}
[job bwa_index.cwl] Removing input staging directory /var/folders/1m/zpv1ttyd3klg2ywkv8c_r4z40000gn/T/dVzS1t
[job bwa_index.cwl] Removing temporary directory /var/folders/1m/zpv1ttyd3klg2ywkv8c_r4z40000gn/T/BcLAm1
{}
Final process status is permanentFail
```

**Comment by jpellman** [comment]
You may want to try posing this question in the [cwltool](https://github.com/common-workflow-language/cwltool) repository instead.  This repository seems to be scoped primarily around the CWL specification.  It also might be easier to diagnose what's going on with an example of the command that you used in addition to the output above.  

My best guess (as a non-expert) is that the output destination is mounted as a read-only volume and that cwltool is unable to write to it, but I'm less familiar with this tool than anyone else here.  I'm slightly confused as to why Apache is showing up in your output- I'm guessing that's unrelated unless it's somehow part of your workflow.

**Comment by Johnnywang92** [comment]
@jpellman thank you for your advice.
The command is 
>  cwl-runner bwa_index.cwl index.yml
And the bwa_index.cwl script:
```
class: CommandLineTool
cwlVersion: v1.0
$namespaces:
  sbg: 'https://www.sevenbridges.com/'
baseCommand:
  - bwa
  - index
inputs:
  - id: algorithm
    type: string?
    inputBinding:
      position: 0
      prefix: '-a'
    doc: |
      BWT construction algorithm: bwtsw or is (Default: auto)
  - id: block_size
    type: int?
    inputBinding:
      position: 0
      prefix: '-b'
    doc: >
      Block size for the bwtsw algorithm (effective with -a bwtsw) (Default:
      10000000)
  - id: reference
    type: File
    inputBinding:
      position: 1
      valueFrom: reference.fa
outputs:
  - id: output
    type: File
    outputBinding:
      glob: $(inputs.reference)
    secondaryFiles:
      - .amb
      - .ann
      - .bwt
      - .pac
      - .sa
doc: |
  Usage:   bwa index [options] <in.fasta>

  Options: -a STR    BWT construction algorithm: bwtsw or is [auto]
           -p STR    prefix of the index [same as fasta name]
           -b INT    block size for the bwtsw algorithm (effective with -a bwtsw) [10000000]
           -6        index files named as <in.fasta>.64.* instead of <in.fasta>.*

  Warning: `-a bwtsw' does not work for short genomes, while `-a is' and
           `-a div' do not work not for long genomes.
requirements:
  - class: ResourceRequirement
    ramMin: 1000
    coresMin: 1
  - class: DockerRequirement
    dockerPull: allenday/bwa-http-docker
  - class: InitialWorkDirRequirement
    listing:
      - $(inputs.reference)
  - class: InlineJavascriptRequirement
```

> You may want to try posing this question in the [cwltool](https://github.com/common-workflow-language/cwltool) repository instead. This repository seems to be scoped primarily around the CWL specification. It also might be easier to diagnose what's going on with an example of the command that you used in addition to the output above.
> 
> My best guess (as a non-expert) is that the output destination is mounted as a read-only volume and that cwltool is unable to write to it, but I'm less familiar with this tool than anyone else here. I'm slightly confused as to why Apache is showing up in your output- I'm guessing that's unrelated unless it's somehow part of your workflow.

**Comment by jpellman** [comment]
That looks like an issue with Docker.  In particular [this line](https://github.com/allenday/bwa-http-docker/blob/98c512e2986b4f8d81465ef50cf6a58f8c0130f4/entrypoint.sh#L4) is being executed and failing within the container.  Not sure what's happening exactly, but [this](https://stackoverflow.com/questions/23537560/docker-build-read-only-file-system) might point you in the right direction.
