### ISSUE TITLE
Issue when filename is expression

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#95]
When in FileDef I have expression for filename, it causes executor to fail:

    Traceback (most recent call last):
      File "/home/luka/venvs/default2/bin/cwltool", line 9, in <module>
        load_entry_point('cwltool==1.0.20150713152138', 'console_scripts', 'cwltool')()
      File "/home/luka/devel/common-workflow-language-upstream/reference/cwltool/main.py", line 281, in main
        move_outputs=args.move_outputs
      File "/home/luka/devel/common-workflow-language-upstream/reference/cwltool/main.py", line 135, in single_job_executor
        for r in jobiter:
      File "/home/luka/devel/common-workflow-language-upstream/reference/cwltool/draft2tool.py", line 374, in job
        j.generatefiles[t["filename"]] = copy.deepcopy(builder.do_eval(t["fileContent"]))
    TypeError: unhashable type: 'dict'

**Comment by tetron** [comment]
Whoops, that's a bug.

**Comment by tetron** [comment]
Fixed and added test.  Please verify and reopen if there are any issues.
